// AUTO-GENERATED by scripts/generate-projects.js — do not edit by hand.
// Add or rename folders inside assets/images/projects/, then run: npm run generate
// (runs automatically before every build)

export interface Project {
  id: string;
  name: string;
  cover: string;
  images: string[];
}

export const PROJECTS: Project[] = [
  {
    id: 'alla',
    name: 'Alla',
    cover: 'assets/images/projects/Alla/IMG_5012.webp',
    images: [
    'assets/images/projects/Alla/IMG_5012.webp',
    'assets/images/projects/Alla/IMG_9757.webp',
    'assets/images/projects/Alla/IMG_9758.webp',
    'assets/images/projects/Alla/IMG_9759.webp',
    'assets/images/projects/Alla/IMG_9760.webp',
    'assets/images/projects/Alla/IMG_9761.webp',
    'assets/images/projects/Alla/IMG_9762.webp',
    'assets/images/projects/Alla/IMG_9763.webp',
    'assets/images/projects/Alla/IMG_9764.webp',
    'assets/images/projects/Alla/IMG_9765.webp',
    'assets/images/projects/Alla/IMG_9766.webp',
    'assets/images/projects/Alla/IMG_9767.webp',
    'assets/images/projects/Alla/IMG_9768.webp',
    'assets/images/projects/Alla/IMG_9769.webp',
    'assets/images/projects/Alla/IMG_9770.webp',
    'assets/images/projects/Alla/IMG_9771.webp',
    'assets/images/projects/Alla/IMG_9772.webp',
    'assets/images/projects/Alla/IMG_9773.webp',
    'assets/images/projects/Alla/IMG_9774.webp',
    'assets/images/projects/Alla/IMG_9775.webp',
    'assets/images/projects/Alla/IMG_9776.webp',
    'assets/images/projects/Alla/IMG_9777.webp',
    'assets/images/projects/Alla/IMG_9778.webp',
    'assets/images/projects/Alla/IMG_9779.webp',
    'assets/images/projects/Alla/IMG_9780.webp',
    'assets/images/projects/Alla/IMG_9781.webp',
    ],
  },
  {
    id: 'raychev',
    name: 'Raychev',
    cover: 'assets/images/projects/Raychev/IMG_0345.webp',
    images: [
    'assets/images/projects/Raychev/IMG_0345.webp',
    'assets/images/projects/Raychev/IMG_0349.webp',
    'assets/images/projects/Raychev/IMG_0350.webp',
    'assets/images/projects/Raychev/IMG_0352.webp',
    'assets/images/projects/Raychev/IMG_0353.webp',
    'assets/images/projects/Raychev/IMG_0354.webp',
    'assets/images/projects/Raychev/IMG_0363.webp',
    'assets/images/projects/Raychev/IMG_0374.webp',
    'assets/images/projects/Raychev/IMG_0377.webp',
    'assets/images/projects/Raychev/IMG_1049.webp',
    ],
  },
  {
    id: 'sergey',
    name: 'Sergey',
    cover: 'assets/images/projects/Sergey/IMG_9676.webp',
    images: [
    'assets/images/projects/Sergey/IMG_9676.webp',
    'assets/images/projects/Sergey/IMG_9677.webp',
    'assets/images/projects/Sergey/IMG_9678.webp',
    'assets/images/projects/Sergey/IMG_9679.webp',
    'assets/images/projects/Sergey/IMG_9680.webp',
    'assets/images/projects/Sergey/IMG_9681.webp',
    'assets/images/projects/Sergey/IMG_9682.webp',
    'assets/images/projects/Sergey/IMG_9683.webp',
    'assets/images/projects/Sergey/IMG_9684.webp',
    'assets/images/projects/Sergey/IMG_9685.webp',
    'assets/images/projects/Sergey/IMG_9686.webp',
    'assets/images/projects/Sergey/IMG_9687.webp',
    'assets/images/projects/Sergey/IMG_9688.webp',
    'assets/images/projects/Sergey/IMG_9689.webp',
    'assets/images/projects/Sergey/IMG_9690.webp',
    'assets/images/projects/Sergey/IMG_9691.webp',
    'assets/images/projects/Sergey/IMG_9692.webp',
    ],
  }
];

export const HERO_IMAGES: string[] = [
  'assets/images/projects/Alla/IMG_5012.webp',
  'assets/images/projects/Raychev/IMG_0345.webp',
  'assets/images/projects/Sergey/IMG_9676.webp',
  'assets/images/projects/Alla/IMG_9757.webp',
  'assets/images/projects/Raychev/IMG_0349.webp',
  'assets/images/projects/Sergey/IMG_9677.webp',
];
