// AUTO-GENERATED by scripts/generate-projects.js — do not edit by hand.
// Add or rename folders inside assets/images/projects/, then run: npm run generate
// (runs automatically before every build)

export interface Project {
  id: string;
  name: string;
  cover: string;
  images: string[];
}

export const PROJECTS: Project[] = [
  {
    id: 'alla',
    name: 'Alla',
    cover: 'assets/images/projects/Alla/IMG_5012.jpg',
    images: [
    'assets/images/projects/Alla/IMG_5012.jpg',
    'assets/images/projects/Alla/IMG_9757.JPG',
    'assets/images/projects/Alla/IMG_9758.JPG',
    'assets/images/projects/Alla/IMG_9759.JPG',
    'assets/images/projects/Alla/IMG_9760.JPG',
    'assets/images/projects/Alla/IMG_9761.JPG',
    'assets/images/projects/Alla/IMG_9762.JPG',
    'assets/images/projects/Alla/IMG_9763.JPG',
    'assets/images/projects/Alla/IMG_9764.JPG',
    'assets/images/projects/Alla/IMG_9765.JPG',
    'assets/images/projects/Alla/IMG_9766.JPG',
    'assets/images/projects/Alla/IMG_9767.JPG',
    'assets/images/projects/Alla/IMG_9768.JPG',
    'assets/images/projects/Alla/IMG_9769.JPG',
    'assets/images/projects/Alla/IMG_9770.JPG',
    'assets/images/projects/Alla/IMG_9771.JPG',
    'assets/images/projects/Alla/IMG_9772.JPG',
    'assets/images/projects/Alla/IMG_9773.JPG',
    'assets/images/projects/Alla/IMG_9774.JPG',
    'assets/images/projects/Alla/IMG_9775.JPG',
    'assets/images/projects/Alla/IMG_9776.JPG',
    'assets/images/projects/Alla/IMG_9777.JPG',
    'assets/images/projects/Alla/IMG_9778.JPG',
    'assets/images/projects/Alla/IMG_9779.JPG',
    'assets/images/projects/Alla/IMG_9780.JPG',
    'assets/images/projects/Alla/IMG_9781.JPG',
    ],
  },
  {
    id: 'raychev',
    name: 'Raychev',
    cover: 'assets/images/projects/Raychev/IMG_0345.JPG',
    images: [
    'assets/images/projects/Raychev/IMG_0345.JPG',
    'assets/images/projects/Raychev/IMG_0349.JPG',
    'assets/images/projects/Raychev/IMG_0350.JPG',
    'assets/images/projects/Raychev/IMG_0352.JPG',
    'assets/images/projects/Raychev/IMG_0353.JPG',
    'assets/images/projects/Raychev/IMG_0354.JPG',
    'assets/images/projects/Raychev/IMG_0363.JPG',
    'assets/images/projects/Raychev/IMG_0374.JPG',
    'assets/images/projects/Raychev/IMG_0377.JPG',
    'assets/images/projects/Raychev/IMG_1049.JPG',
    ],
  },
  {
    id: 'sergey',
    name: 'Sergey',
    cover: 'assets/images/projects/Sergey/IMG_9676.JPG',
    images: [
    'assets/images/projects/Sergey/IMG_9676.JPG',
    'assets/images/projects/Sergey/IMG_9677.JPG',
    'assets/images/projects/Sergey/IMG_9678.JPG',
    'assets/images/projects/Sergey/IMG_9679.JPG',
    'assets/images/projects/Sergey/IMG_9680.JPG',
    'assets/images/projects/Sergey/IMG_9681.JPG',
    'assets/images/projects/Sergey/IMG_9682.JPG',
    'assets/images/projects/Sergey/IMG_9683.JPG',
    'assets/images/projects/Sergey/IMG_9684.JPG',
    'assets/images/projects/Sergey/IMG_9685.JPG',
    'assets/images/projects/Sergey/IMG_9686.JPG',
    'assets/images/projects/Sergey/IMG_9687.JPG',
    'assets/images/projects/Sergey/IMG_9688.JPG',
    'assets/images/projects/Sergey/IMG_9689.JPG',
    'assets/images/projects/Sergey/IMG_9690.JPG',
    'assets/images/projects/Sergey/IMG_9691.JPG',
    'assets/images/projects/Sergey/IMG_9692.JPG',
    ],
  }
];

export const HERO_IMAGES: string[] = [
  'assets/images/projects/Alla/IMG_5012.jpg',
  'assets/images/projects/Raychev/IMG_0345.JPG',
  'assets/images/projects/Sergey/IMG_9676.JPG',
  'assets/images/projects/Alla/IMG_9757.JPG',
  'assets/images/projects/Raychev/IMG_0349.JPG',
  'assets/images/projects/Sergey/IMG_9677.JPG',
];
